server:
  port: 8090
  servlet:
    context-path: /dna/practice

spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/portal
#    username: vtw
#    password: vtw123#

# sql 데이터 삽입 관련 설정 주석처리
#  data: classpath:data.sql

  jpa:
    show-sql: true # sql 로그 출력
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
